name: egs
description: Productivity Platform

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.2
  appflowy_board: ^0.1.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.6
  flutter_multi_formatter: ^2.12.4
  flutter_svg: ^2.0.8
  fl_chart: ^0.68.0
  flex_color_scheme: ^7.3.1
  graphql_flutter: ^5.1.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  lottie: ^3.1.0
  path: ^1.9.0
  provider: ^6.1.1
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  url_launcher: ^6.2.4
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
